#!/usr/bin/env ruby

require './lib/dom_tree'
require 'continuous_builder'
require 'haml'
require 'sass'
require 'sass/plugin'
#require 'jabs'
require 'erb'

module DomTree
  class Builder < ContinuousBuilder
    watches :bookmarklet,
      :files => DomTree.app/'bookmarklet'/'source.js.erb',
      :update => :build_bookmarklet

    watches :haml,
      :files => DomTree.app/'**'/'*.html.haml',
      :module => Haml
         
    watches :sass,
      :files => DomTree.app/'**'/'*.css.sass',
      :module => Sass,
      :style => :compressed
=begin
    watches :embedded_jabs,
      :files => DomTree.app/'embedded'/'**'/'*.js.jabs',
      :module => Jabs
=end
    watches :embedded_resources,
      :files => DomTree.app/'embedded'/'**'/'*{.js,.html}',
      :update => :build_embedded,
      :wait_for_all_edits => true

    watches :vendor_js,
      :files => DomTree.vendor/'**'/'*.js',
      :update => :build_embedded,
      :wait_for_all_edits => true

    def build_bookmarklet path
      template = ERB.new(path.read)
        
      f = (DomTree.app/'public'/'bookmarklet.js').open 'w+'
      f.write template.result(binding)
      f.close
    end
    
    def build_embedded path
      scripts = []
      vendor = DomTree.vendor
      
      scripts << (vendor/'jquery'/'jquery-1.2.6.js')
      scripts << (vendor/'drag_drop'/'jquery.event.drag-1.0.js')
      scripts << (vendor/'drag_drop'/'jquery.event.drop-1.0.js')
      scripts << (vendor/'keybinder'/'jquery.keybinder.js')
      scripts << (vendor/'autocomplete'/'jquery.autocomplete.js')
      scripts << (vendor/'designmode'/'jquery.designmode.js')
      scripts << (vendor/'jquery_border_layout'/'jquery.border_layout-0.0.0.js')
      
      Pathname.glob(DomTree.app/'embedded'/'**'/'*.html').each do |script|
        flat = script.read
        flat.gsub! "\r\n", ""
        flat.gsub! "\n", ""
        flat.gsub! /\/\*.*\*\//, "" 
        flat.gsub! /\"/ , "\\\""
        name = script.basename.to_s.gsub('.html', '')
        jquery = "jQuery.#{name} = jQuery(\"#{flat}\");"       
        io = StringIO.new jquery
        scripts << io
      end 
      
      Pathname.glob(DomTree.app/'embedded'/'**'/'*.js').each do |script|
        scripts << script
      end
      
      f = File.open(DomTree.app/'public'/'embedded.js', 'w+')
      f.write scripts.map{|script| script.read}.join("\n\n")
      f.close()
    end
  end
end

builder = DomTree::Builder.new
builder.build_all
builder.build_continuously
